name: release-draft

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  create-release-draft:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'
        
    - name: Build windows
      run: env GOOS=windows GOARCH=amd64 go build -o bin/win/ -ldflags "-X 'github.com/Appelfeldt/totpauth/cmd/totpauth.BuildVersion=${{ github.ref_name }}'" -v ./...

    - name: Archive windows
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'totpauth-win-amd64.zip'
        path: bin/win/

        
    - name: Build linux-amd64
      run: env GOOS=linux GOARCH=amd64 go build -o bin/linux-amd64/ -ldflags "-X 'github.com/Appelfeldt/totpauth/cmd/totpauth.BuildVersion=${{ github.ref_name }}'" -v ./...
      
    - name: Archive linux-amd64
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'totpauth-linux-amd64.zip'
        path: bin/linux-amd64/
        
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: true
        prerelease: false
        release_name: ${{ github.ref_name }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: upload windows artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: totpauth-win-amd64.zip
        asset_name: totpauth-win-amd64.zip
        asset_content_type: application/zip

    - name: upload linux-amd64 artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: totpauth-linux-amd64.zip
        asset_name: totpauth-linux-amd64.zip
        asset_content_type: application/zip
